services:
  web:
    image: temnetiksstoreregistry.azurecr.io/netiks-store/web:v1.2.1

  gateway:
    image: temnetiksstoreregistry.azurecr.io/netiks-store/gateway:v1.0.0

  identity-service:
    image: temnetiksstoreregistry.azurecr.io/netiks-store/identity-service:v1.0.0

  vendor-service:
    image: temnetiksstoreregistry.azurecr.io/netiks-store/vendor-service:v1.0.0

  catalog-service:
    image: temnetiksstoreregistry.azurecr.io/netiks-store/catalog-service:v1.0.0

  media-service:
    image: temnetiksstoreregistry.azurecr.io/netiks-store/media-service:v1.0.0

  admin-service:
    image: temnetiksstoreregistry.azurecr.io/netiks-store/admin-service:v1.0.0
